services:
  sqlserver:
    container_name: sqlserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    volumes:
      - ./scripts:/scripts
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    mem_limit: 4g
    cpus: 2

volumes:
  sqlserver_data:
    driver: local
